log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:password@localhost:5432/listener?sslmode=disable

listener:
  addr: :8000

networks:
  keys:
    - name: 'Ethereum'
      rpc: "https://mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Polygon'
      rpc: "https://polygon-mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Avalanche'
      rpc: "https://avalanche-mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Goerli'
      rpc:  "https://goerli.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Sepolia'
      rpc:  "https://sepolia.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'BSC Testnet'
      rpc:  "https://bsc-testnet.publicnode.com"


api:
  endpoint: "https://api.rarify.tokend.io/v1/chains"
  auto_init: true

meta_data:
  header: "66613161666237613a"
  footer: "3b"

chain_listener:
  pause_time: 2

#meta_data:
#  header: "fa1afb7a:"
#  footer: ";a"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: back-listener
  service_port: 80
