log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:password@localhost:5432/listener?sslmode=disable

listener:
  addr: :8000

networks:
  keys:
    - name: 'Goerli'
      chain_id: 5
      rpc:  "https://goerli.infura.io/v3/5aabf6bd4d384c288d6f85d3d6278234"
#    - name: 'Fuji'
#      rpc:  "https://avalanche-fuji.infura.io/v3/5aabf6bd4d384c288d6f85d3d6278234"
    - name: 'BSC Testnet'
      chain_id: 97
      rpc:  "https://bsc-testnet.publicnode.com"


api:
  endpoint: "https://api.rarify.tokend.io/v1/chains"
  auto_init: true

meta_data:
  header: "66613161666237613a"
  footer: "3b"

chain_listener:
  pause_time: 500
  abi_path: "./pkg/contract/erc20/erc20.abi"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: back-listener
  service_port: 80
