log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:password@localhost:5432/listener?sslmode=disable

listener:
  addr: :8000

networks:
  list:
    - name: 'Ethereum'
      rpc: "https://mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Polygon'
      rpc: "https://polygon-mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Avalanche'
      rpc: "https://avalanche-mainnet.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
    - name: 'Georly'
      address: "0x07865c6e87b9f70255377e024ace6630c1eaa37f"
      rpc:  "https://goerli.infura.io/v3/5afc5eb6b4424ad39f8c0db22125074a"
api:
  endpoint: "https://api.rarify.tokend.io/v1/chains"
  auto_init: false

tx_wrapper:
  header: 66613161666237613a
#  header_string: "fa1afb7a:"


cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: back-listener
  service_port: 80
