log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:password@localhost:5432/listener?sslmode=disable

listener:
  addr: :8000

networks:
  keys:
    - name: 'Goerli'
      chain_id: 5
      rpc:  "https://goerli.infura.io/v3/"
    - name: 'Fuji'
      chain_id: 43113
      rpc:  "https://avalanche-fuji.infura.io/v3/"
    - name: 'BSC Testnet'
      chain_id: 97
      rpc:  "https://data-seed-prebsc-2-s3.binance.org:8545/"
    - name: 'Ethereum'
      chain_id: 1
      rpc: "https://mainnet.infura.io/v3/"
    - name: 'Avalanche'
      chain_id: 43114
      rpc: "https://avalanche-mainnet.infura.io/v3/"
    - name: 'Sepolia'
      chain_id: 11155111
      rpc:  "https://sepolia.infura.io/v3/"


api:
  endpoint: "https://api.rarify.tokend.io/v1/chains"
  auto_init: true

meta_data:
  header: "66613161666237613a"
  footer: "3b"

chain_listener:
  pause_time: 500
  abi_path: "/fgo/src/github.com/dl-only-tokens/back-listener/pkg/contract/erc20/erc20.abi"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: back-listener
  service_port: 80
